local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 1
    publish_frequency: 1
    static_map: false
    rolling_window: true
    transform_tolerance: 10.0
    width: 15.0
    height: 15.0
    meter_scoring: true